### ISSUE TITLE
Enable loading state_dicts in active learning dataset

### ISSUE THREAD

**Issue by janfreyberg** [ElementAI/baal#10]
**Is your feature request related to a problem? Please describe.**
We currently are able to get a state dict for `ActiveLearningDataset`, but not load a state dict. This should be enabled to make resuming from pre-empted states easier.

**Describe the solution you'd like**

A `load_state_dict` method that assigns the `labelled` value from the state dict to the object.

**Describe alternatives you've considered**

Adding this method to the active learning loop, instead; but this is a bit closer to where the data that is saved / loaded is relevant.

Flagged by @IssamLaradji

**Comment by parmidaatg** [comment]
Solved in #13
