### ISSUE TITLE
two bugs in experiments/segmentation/utils.py

### ISSUE THREAD

**Issue by pieterbl86** [ElementAI/baal#108]
**Describe the bug**
Two bugs in experiments/segmentation/utils.py:

1. forgot to import torch (causing an error on line 103)
2. index error in the self.alpha.gather function in class FocalLoss

**To Reproduce**
errors occur when running the unet example code:
python experiments/segmentation/unet_mcdropout_pascal.py

Some advices:
* import torch (line 6)
* remove line 122: at = self.alpha.gather(0, target.data.view(-1))
* on line 122 insert: select = (target!=0).type(torch.LongTensor).cuda()
* on line 123 insert: at = self.alpha.gather(0,select.data.view(-1))
* thanks to this URL: https://github.com/clcarwin/focal_loss_pytorch/issues/4

**Expected behavior**
Errors are solved, when applying the advices above. Maybe make line 122 dynamic when not using cuda. 

**Version (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python: 3.7
 - BaaL version: 1.2.1
 - CUDA: 10.1
 - cuDNN: 7.6.5
 - Pytorch: 1.7.0+cu101
 - torchvision: 0.8.1+cu101

**Additional context**
The alpha bug causes a CUDA or cuDNN assertion error.

**Comment by Dref360** [comment]
I'm working on it! I'll submit a fix today.

**Comment by pieterbl86** [comment]
> I'm working on it! I'll submit a fix today.

Great! I wonder if the "import torch" error will appear at your system. It might have been caused by some wrong environmental setting in my programming IDE (Visual Studio Code with Python bindings).

**Comment by pieterbl86** [comment]
@Dref360 thank you very much for the fast update. I will pull the new software and test it. For now, I will close this issue.
