### ISSUE TITLE
Importing `baal` fails when the `transformers` optional dep is missing

### ISSUE THREAD

**Issue by hadim** [ElementAI/baal#114]
This is problematic when building the conda package since it does not include the optional dep `transformers`.

I see two solutions:

- make `transformers` a required dep
- add a conditional check to https://github.com/ElementAI/baal/blob/26bde3a9ef68454cb2795de3784cde4032fc0391/src/baal/transformers_trainer_wrapper.py so `transformers` is not imported if missing that way `baal` can still be used without `transformers`.

**Comment by hadim** [comment]
xref with https://github.com/conda-forge/baal-feedstock/pull/1#discussion_r595370852

**Comment by Dref360** [comment]
Hello,
I think `transformers` is already a required deps.

https://github.com/ElementAI/baal/blob/master/requirements.txt#L13 

Is there something that we are missing? :) 

I think setting it as an optional deps would be great.

**Comment by hadim** [comment]
i said this because of this comment https://github.com/ElementAI/baal/blob/26bde3a9ef68454cb2795de3784cde4032fc0391/src/baal/transformers_trainer_wrapper.py#L6

Is it obsolete?

**Comment by Dref360** [comment]
Oh right! Yeah I think this comment is obsolete for now. We should assess whether we want transformers as a required deps or not.

Thank you!

**Comment by hadim** [comment]
Ok let me know when you took a decision for https://github.com/conda-forge/baal-feedstock/pull/1

**Comment by Dref360** [comment]
I put HF as an optional dependency, do we need to push a new version to fix the conda recipe or it's good now?

**Comment by hadim** [comment]
A new version must be uploaded to pypi since the source of truth for the code is the sdist archive on pypi (with a sha256 hash). I closed the PR for 1.3.0 on the feedstock and will wait for 1.3.1.
