### ISSUE TITLE
Support Random target_transform in ALDataset

### ISSUE THREAD

**Issue by Dref360** [ElementAI/baal#14]
**Is your feature request related to a problem? Please describe.**
In Segmentation, we need to augment both the target and the input.
At test time, only the transform is updated.

**Comment by janfreyberg** [comment]
presumably this will have to be a function that takes in both input and target at the same time? To make sure they get augmented in the same way?

**Comment by Dref360** [comment]
Yeah, the torchvision API is not stable yet, but they are going toward something similar. I guess we're kinda bound to whatever torchvision is doing in most cases.

Like CIFAR10 use `transform` and `target_transforms`
https://pytorch.org/docs/stable/torchvision/datasets.html#cifar

But Pascal use `transforms`
https://pytorch.org/docs/stable/torchvision/datasets.html#torchvision.datasets.VOCSegmentation

Should we be even more flexible and add a **kwargs that would switch any params?

**Comment by janfreyberg** [comment]
Yeah, maybe that's the right thing to do. be flexible. I use the `transforms` format in other projects but if we keep it flexible we can continue to support segmentation / classification!

**Comment by Dref360** [comment]
What do you think of:

```python
ActiveLearningDataset(_datatset, ..., transform=test_transform, target_transform=test_target)

def __init__(self, dataset, ..., **kwargs):
    self.pool_overrides = kwargs
	...

def pool(self):
    pool = Subset(...)
    for key,val in self.pool_overrides.items():
    	setattr(key, val)

```
