### ISSUE TITLE
Please provide an example for multilayer perceptron regression too in experiments section.

### ISSUE THREAD

**Issue by ayu1729** [ElementAI/baal#145]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by parmidaatg** [comment]
Hi @ayu1729, Sure I will make one this week :)

**Comment by Dref360** [comment]
Hello,

I added an example in this PR: https://github.com/ElementAI/baal/pull/150
let me know what you think.
