### ISSUE TITLE
active_learning_image_classification.py fails because of method resolution issue

### ISSUE THREAD

**Issue by GeorgePearse** [ElementAI/baal#190]
**Describe the bug**
active_learning_image_classification.py fails because of method resolution issue

![image](https://user-images.githubusercontent.com/47161914/155517032-be5eb39d-5af1-423c-b366-48df105655b8.png)

**To Reproduce**

python3 active_learning_image_classification.py

**Comment by Dref360** [comment]
Thanks for the info, I should be able to take a look on Monday.

We would like to deprecate our custom Lightning integration in favor of Lightning-flash that supports BaaL out of the box.
https://devblog.pytorchlightning.ai/active-learning-made-simple-using-flash-and-baal-2216df6f872c

We should at least add a notice to this example.
