### ISSUE TITLE
BatchBALD implementation

### ISSUE THREAD

**Issue by anurag-umich** [ElementAI/baal#52]
It just selects a permutation of points present in the batch but not all combinations as mentioned in the paper. The number of combinations would be c^b according to the paper but according to your code it will have b or b[max_size] combinations. Am I missing anything?

Lets say there are total 100 points , 4 classes and 10 iterations
so prediction tensor would be of shape (100,4,10)

now lets say I am creating a set of points and I have 4 points in the history = [3,18,45,60]
now selected in your code would be predictions[np.random.permutation(history[:MAX_SELECTED]]
 it would jusr randomly permute these indices in history and subset prediction tensor for those values. These are not combinations in my opinion. I would assume to sample combination I will need to create a tensor of size 4^5 x 10 (4 is num classes and 5 is the batch size) 

https://github.com/ElementAI/baal/blob/377ea8ed1bb78936f79d2a343bfe6835668446a3/src/baal/active/heuristics/heuristics.py#L287

I looked at author's original implementation and they seem to have implemented the sampling logic as expected. (https://github.com/BlackHC/BatchBALD/blob/master/src/joint_entropy/sampling.py)

Thanks in advance!

**Comment by Dref360** [comment]
Yes the fix is currently in a PR. https://github.com/ElementAI/baal/pull/50

It should be merged shortly. Sorry

**Comment by anurag-umich** [comment]
Sure. I can review it.

**Comment by Dref360** [comment]
Fixed in BaaL 1.2. Thank you for your help!
