### ISSUE TITLE
BatchBald joint entropy generator

### ISSUE THREAD

**Issue by anurag-umich** [ElementAI/baal#54]
https://github.com/ElementAI/baal/blob/1c2b8f32431091ea7b089f5fd93457e75c6586a5/src/baal/active/heuristics/heuristics.py#L369

Shouldn't this be done like this instead?

for idx in range(0, exp_y.shape[0], step):
            b_preds = exp_y[idx: idx+step]

The successive indices are 0, 256, 512 and so on so multiplying them with step would not give the right values.

Let me know if I am missing anything.

Thanks!

**Comment by Dref360** [comment]
You are right. I submitted a fix. Sorry for the inconvenience (again)
