### ISSUE TITLE
Allow configurations of how "iterations" is handled by ModelWrapper to preserve memory

### ISSUE THREAD

**Issue by janfreyberg** [ElementAI/baal#6]
When running the `predict_*` methods of ModelWrapper, the same batch size that works during training / testing may cause out-of-memory errors because [we replicate the data in each batch](https://github.com/ElementAI/baal/blob/master/src/baal/modelwrapper.py#L332) so the memory footprint will be e.g. 10x the memory footprint during training.

I think it may make sense to allow setting that multiple iterations of the data through the model are done in sequence (e.g. in a for-loop). This will probably (haven't tested this) be a bit slower than replicating the data but it's a speed / memory trade-off that the user could decide themselves. I am thinking this could be an argument to `ModelWrapper.__init__`

I think this would match user expectations (that picking a batch size that fits in memory during training will also fit during prediction).

If people agree, I can implement this with @rafapi (who ran into this issue in the first place when using a local GPU!)

**Comment by Dref360** [comment]
Good idea, way more User-friendly.

I just did a quick test and it would be 50% slower (see below).
Should we keep the batched mode by default and catch the RunTime error to inform the user?


```python
from torchvision.models import vgg16
import torch
model = vgg16().cuda().eval()
inp = torch.randn(1, 3, 224, 224).cuda()
inp_batched = torch.randn(10, 3, 224, 224).cuda()

# Burnin to initialize cuda
model(inp)

# TEST
%timeit [model(inp) for _ in range(10)]
# 242 ms ± 266 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit model(inp_batched)
# 169 ms ± 2.82 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)



```

**Comment by parmidaatg** [comment]
Yes, I agree with Fred, we should keep the replication as default but that is true that we need the simple for loop support. For Classification, it is not a problem but the more complicated the task, it would happen. for segmentation, we just use smaller batch size in Active Learning Loop and that would do but for localization, I was not able to do any trick, so I reimplemented the for loop version for my experiment. That would be cool to support both 👍
