### ISSUE TITLE
BatchBALD doesnt work with more than 3 dimensions

### ISSUE THREAD

**Issue by kazimpal87** [ElementAI/baal#63]
The docstring for BatchBALD._sample_from_history shows the probs argument to be:

` probs (Tensor[batch, classes, ..., iterations]): Tensor to be sampled from.`

However, when using more than 3 dimensions (for example to represent different pixels in an image), the line:

`probs = probs.permute(0, 2, 1)`

in _draw_choices crashes because it expects exactly 3 dimenions.

**Comment by Dref360** [comment]
Hello,
The doc is wrong.
We could probably make BatchBALD works on multiple inputs without too much effort. Of course, because BatchBALD does not work with generators, it may be hard to use.

I could probably work on it next week if that's okay with you?
In the meantime, PRs are welcome :)
