### ISSUE TITLE
A question about ActiveLearningDataset.

### ISSUE THREAD

**Issue by sakuraiiiii** [ElementAI/baal#65]
Hi,I want to construct my own dataset like the following:
```python
import torch
from torch.utils.data import Dataset
from baal.active.dataset import ActiveLearningDataset

a = []
for i in range(20):
    a.append(torch.rand(10))

data = Data(a)
pool = ActiveLearningDataset(data)
```
and I want to label several data in the dataset:
```python
pool.label(index=4, value=torch.tensor([0]))
```
But I get the error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in 
----> 1 pool.label(index=4, value=torch.tensor([0]))

 in label(self, index, value)
    159             if self.can_label and val is not None:
    160                 print(self._dataset.label)
--> 161                 self._dataset.label(index, val)
    162                 self._labelled[index] = 1
    163             elif self.can_label and val is None:

TypeError: 'NoneType' object is not callable
```
I read the original code, and find the ```self._dataset.label``` is None.Is the above code right or is this a bug?

**Comment by Dref360** [comment]
Hello,

Would your class `Data` have a field named `label`?

This is definitely a bug on our side, we should check that `self._dataset.label` is a `Callable`.

Thank you for raising this issue.

I'll explain the behavior here for other users and I would add this to our FAQ as well.

In Baal, we allow both a research mode and a production mode.

* Research mode
  * Assume that you already have the labels, so we ignore the `value` even if it is not None.
* Production mode
  * To label something, we assume that the inner dataset has a method named `label` and we forward the value to it. 


We do have a tutorial on how to use Baal in Production. It uses our class `FileDataset` which does have a `label` method.

https://baal.readthedocs.io/en/latest/notebooks/baal_prod_cls.html


Thanks again for reporting this issue!

**Comment by sakuraiiiii** [comment]
Oh,sorry.I forgot to copy the class ```Data``` above.Thank you for your advice.This is the original class ```Data```:
```python
class Data(Dataset):
    def __init__(self, feature, label=None):
        self.feature = feature
        self.label = label
    
    def __getitem__(self, index):
        if self.label:
            return self.feature[index], self.label[index]
        else:
            return self.feature[index]
    
    def __len__(self):
        return len(self.feature)
```
However I'm still confused about how to make the class ```Data``` have a field named ```label```?Does you mean that I should define a ```label``` method for the unlabelled data to query the label?
```python
class Data(Dataset):
    def __init__(self, feature):
        self.feature = feature
    
    def __getitem__(self, index):
        return self.feature[index]
    
    def __len__(self):
        return len(self.feature)

    def label(self, index):
        return self.feature[index].sum()
```
when I use ```pool.label(index=4)```,it still has a problem:
```python
c:\users\anaconda3\lib\site-packages\baal\active\dataset.py:170: UserWarning: The dataset is able to label data, but no label was provided.
                                 The dataset will be unchanged from this action!
                                 If this is a research setting, please set the
                                  `ActiveLearningDataset.can_label` to `False`.

  """, UserWarning)
```
Could you give me an example?Thank you very much.

**Comment by Dref360** [comment]
yes a `label` method sorry.

The warning you see is normal. If it gets too verbose, we should suppress it.


If the labels are already available then you don't need this method.

But in the case of a live application you would get something like this:

```python
# Some definitions
your_heuristic = BALD()
pool = active_dataset.pool
your_predictions = ModelWrapper.predict_on_dataset(pool, ...)
# The shape of `your_predictions` is [len(pool), n_classes, ..., iterations]
# Get the next batch of samples to label. Note: These indices are according to the pool.
ranks = your_heuristic(your_predictions)

# Now let's ask a human to label those samples.
labels = ask_a_human(ranks, pool)

# To edit the dataset labels, you can now add those labels to your dataset. Still, the indices are according to the pool.
active_dataset.label(ranks, labels)
```

See how we make the `label` method in `FileDataset` [here](https://github.com/ElementAI/baal/blob/master/src/baal/active/file_dataset.py#L53)

**Comment by Dref360** [comment]
If you don't know the label, you should just return a dummy value for the labels.

I would propose something like this:
```python
class Data(Dataset):
    def __init__(self, feature, label=None):
        self.feature = feature
        self.lbl = label or [-1] * len(feature)
    
    def __getitem__(self, index):
        return self.feature[index], self.lbl[index]
    
    def __len__(self):
        return len(self.feature)

	def label(self, index, value):
		self.lbl[index] = value
```

**Comment by Dref360** [comment]
I'm currently working on our FAQ. here is a section that I would like to add on the split. If there is something missing, please let me know and I'll add it.

## How can I specify that a label is missing and how to label it.

The source of truth for what is labelled is the `ActiveLearningDataset._labelled` array.
This means that we will never train on a sample if it is not labelled according to this array.
This array determines the split between the labelled and unlabelled datasets.

```python
# Let ds = D, the entire dataset with labelled/unlabelled data.
ds = YourDataset()
al_dataset = ActiveLearningDataset(ds, ...)
# For convenience, let's label 10 samples at random.
# But you can provide the `labelled` array to ActiveLearningDataset
# if you already have labels.
al_dataset.label_randomly(10)
pool = al_dataset.pool
```

From a rigorous point of view: $D = ds$, $D_L=al\_dataset$ and $D_U = D \setminus D_L = pool$.
Then, we train our model on $D_L$ and compute the uncertainty on $D_U$. The most uncertain samples are labelled and added to $D_L$, removed from $D_U$.

Let a method `query_human` performs the annotations, we can label our dataset using indices relative to $D_U$. This assumes that your dataset class `YourDataset` has a method named `label` which has the following definition: `def label(self, idx, value)` where we give the label for indice `idx`. There the indice is not relative to the pool, so you don't have to worry about it.

**Comment by sakuraiiiii** [comment]
That's very clear.Thank you very much.
