### ISSUE TITLE
DropConnect wrapped model could not be parallelized 

### ISSUE THREAD

**Issue by Valentyn1997** [ElementAI/baal#91]
**Describe the bug**
While using the `baal.bayesian.MCDropoutConnectModule` wrapper, it is impossible to train the model with multiple GPUs.
One gets the following error:

`RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)`

**To Reproduce**
Simple training with PyTorch DataParallel and at least 2 GPUs. 

**Expected behavior**
A possible solution would be to remove the dynamic `forward` method re-assignment for Conv and Dense layers. This issue is described here: https://github.com/pytorch/pytorch/issues/8637

**Comment by Dref360** [comment]
Hello,

Thank you for submitting this issue! 
I'll look into it on Monday. We are also open to contributions if you already have a fix working.
